Initial files
scratch-contributors/scratch-contributors.github.io pull request #3
Opened 2021-05-30 19:12 UTC by FunctionalMetatable

DONT MERGE! I'm working on the website here for some reason

2021-05-30 21:41 UTC, leahcimto commented
This is looking amazing so far!

2021-05-31 05:33 UTC, FunctionalMetatable commented
> This is looking amazing so far!

not really there isn't any styling yet :P

2021-05-31 11:20 UTC, leahcimto commented
> > This is looking amazing so far!
> 
> not really there isn't any styling yet :P

I meant the set up :P

2021-05-31 11:21 UTC, FunctionalMetatable commented
i'm also making the bios look like forum posts

2021-05-31 11:23 UTC, leahcimto commented
Cool!

2021-05-31 11:25 UTC, leahcimto commented
Also just FYI you can make a branch on this repo if you would like in the future

2021-05-31 11:26 UTC, FunctionalMetatable commented
> Also just FYI you can make a branch on this repo if you would like in the future

yeah ik. i dont want to be playing around with replit in this repository so i used my fork. i think you guys can commit into my fork though

2021-05-31 12:07 UTC, leahcimto commented
sorry for the failed workflow, my bad

2021-05-31 13:19 UTC, leahcimto commented
<img width="1428" alt="Screen Shot 2021-05-31 at 9 19 22 AM" src="https://user-images.githubusercontent.com/68165163/120199509-5149c400-c1f1-11eb-9dff-7aa7ab541db6.png">
Are you getting this

2021-05-31 13:39 UTC, FunctionalMetatable commented
> https://user-images.githubusercontent.com/68165163/120199509-5149c400-c1f1-11eb-9dff-7aa7ab541db6.png
> 
> Are you getting this

nope

2021-05-31 13:49 UTC, FunctionalMetatable commented
Also, if you'd like to preview it you can see it [here](https://functionalmetatable.github.io/scrs/) as the workflow automatically deploys it

2021-05-31 14:14 UTC, leahcimto commented
Do you see it when you open it locally?

2021-05-31 14:16 UTC, FunctionalMetatable commented
> Do you see it when you open it locally?

I havent opened it locally yet (thats why theres a million commits). I think I fixed it already, but I'll open it locally soon (I was using replit)

2021-05-31 14:19 UTC, leahcimto commented
Ok, I'll open it with replit. What language did you choose?

2021-05-31 14:20 UTC, leahcimto commented
> Also, if you'd like to preview it you can see it [here](https://functionalmetatable.github.io/scrs/) as the workflow automatically deploys it
> 
> EDIT: could somebody help w/ the css please

I'll try.

2021-05-31 14:24 UTC, leahcimto commented
@FunctionalMetatable

2021-05-31 14:30 UTC, FunctionalMetatable commented
> Ok, I'll open it with replit. What language did you choose?

bash. I only used repl for editing it though. I previewed it in my fork.

btw I thought I sent a reply already

2021-05-31 14:32 UTC, leahcimto commented
> btw I thought I sent a reply already

Odd... I didn't get one...

2021-05-31 18:53 UTC, gosoccerboy5 commented
If you merge this, make sure to squash and merge or else you'll have a huge commit history :P

2021-05-31 19:03 UTC, leahcimto commented
lol

2021-05-31 19:04 UTC, leahcimto commented on src/components/Header.vue
> +        <img src="/icon.png" width="50px" height="50px">
Is the icon showing for you? It's not for me.

2021-05-31 19:06 UTC, FunctionalMetatable commented on src/components/Header.vue
> +        <img src="/icon.png" width="50px" height="50px">
are you previewing on my fork? on forks it doesn't show because it goes to the root directory

2021-05-31 19:07 UTC, leahcimto commented on src/components/Header.vue
> +        <img src="/icon.png" width="50px" height="50px">
Yes

2021-05-31 19:09 UTC, FunctionalMetatable commented
https://github.com/FunctionalMetatable/scrs/blob/ac7528bbcccb4ae1c783cbaf2f61ea1cf04de317/src/pages/contributors.vue#L8

not sure why it's not looping over the managers table...

@jeffalo/somebody plz explain

2021-05-31 21:31 UTC, gosoccerboy5 commented
Maybe add this rule to the CSS?
```css
.nav-item a {
    padding: 30px 10px 30px 10px;
    transition-duration: 0.1s;
}
```
that way you don't have wacky behavior like this:
<img width="318" alt="Screen Shot 2021-05-31 at 4 29 34 PM" src="https://user-images.githubusercontent.com/82768218/120243511-68a6a280-c22d-11eb-86df-4237e8621381.png">
and when the user hovers over a nav link there's a sort of "fade" effect

2021-05-31 21:56 UTC, gosoccerboy5 commented on src/components/Header.vue
> -  padding: 22px 16px;
I believe you may have needed this rule

2021-06-01 06:59 UTC, FunctionalMetatable commented on src/components/Header.vue
> -  padding: 22px 16px;
nope, i thought i replaced it w/ yours

2021-06-01 08:53 UTC, FunctionalMetatable commented
Before merging, please tell me because there is some config needed for the main repo

2021-06-01 17:22 UTC, FunctionalMetatable commented
Finished. Please review it!
@leahcimto @gosoccerboy5

2021-06-01 17:40 UTC, gosoccerboy5 requested changes

2021-06-01 17:40 UTC, gosoccerboy5 commented on src/components/Header.vue
> +  padding: 15px 5px 5px 10px;
maybe change this declaration to `padding: 20px 5px 5px 10px;`? rn the site looks like this:
<img width="359" alt="Screen Shot 2021-06-01 at 12 38 16 PM" src="https://user-images.githubusercontent.com/82768218/120367246-42890d00-c2d6-11eb-9968-8c02d6638c95.png"> (the white at the top is my search bar btw)
the site looks epic gamer otherwise

2021-06-01 17:40 UTC, gosoccerboy5 commented on src/components/Footer.vue
> +    Roboto, "Helvetica Neue", Arial, sans-serif
maybe add a small declaration `border-radius: 2px;` to make the button look a teensy bit better

2021-06-01 19:29 UTC, FunctionalMetatable commented on src/components/Footer.vue
> +    Roboto, "Helvetica Neue", Arial, sans-serif
the button is transparent

2021-06-01 19:31 UTC, FunctionalMetatable commented on src/components/Header.vue
> +  padding: 15px 5px 5px 10px;
done

2021-06-01 20:58 UTC, leahcimto commented
Looks great so far! Just a few comments:

2021-06-01 21:02 UTC, leahcimto reviewed
Could you remove the "postpercent/ocular"  on the contributors page? I just think it looks a bit off and not all contributors contribute in the forums.

2021-06-01 21:03 UTC, leahcimto reviewed
With the list on the homepage, please make that not centered as it looks weird with the bullets all on the left.

2021-06-01 21:05 UTC, leahcimto reviewed
Could you style the change theme button? Also, I don't have an option for a light mode (might be because I have system dark mode) Could you please fix that :)

2021-06-01 21:06 UTC, leahcimto requested changes
Could you please make the contributors

2021-06-01 21:06 UTC, leahcimto commented on src/components/Header.vue
> +      <a href="https://scratch.mit.edu/studios/26371714">Scratch Studio</a>
Could you please make this open in a new tab

2021-06-01 21:06 UTC, leahcimto commented
Other than that it looks good!

2021-06-01 21:18 UTC, FunctionalMetatable commented on src/components/Header.vue
> +      <a href="https://scratch.mit.edu/studios/26371714">Scratch Studio</a>
done

2021-06-01 21:19 UTC, leahcimto commented
Could you style the theme toggle?

2021-06-01 21:23 UTC, FunctionalMetatable commented
> Could you style the theme toggle?

I took the ugly background from the button. should I actually use a button for it? imo it looks good now

2021-06-01 21:32 UTC, gosoccerboy5 approved these changes

2021-06-01 21:37 UTC, leahcimto commented
The button isn't working for me for some reason...

2021-06-01 21:38 UTC, FunctionalMetatable commented
> The button isn't working for me for some reason...

if you're previewing on my fork it won't work because I did changes to the router (see one of the latest commits)

2021-06-01 21:41 UTC, leahcimto approved these changes
Thank you so so much for doing this @FunctionalMetatable!! It all looks great locally.

2021-06-01 21:41 UTC, leahcimto commented
<img width="765" alt="Screen Shot 2021-06-01 at 5 41 32 PM" src="https://user-images.githubusercontent.com/68165163/120393839-9c063180-c300-11eb-9d39-2e564cfe8c56.png">
Wait- just saw this.

2021-06-01 21:41 UTC, FunctionalMetatable commented
should I merge?

2021-06-01 21:42 UTC, leahcimto commented
Is that happening to you?

2021-06-01 21:42 UTC, FunctionalMetatable commented
> <img alt="Screen Shot 2021-06-01 at 5 41 32 PM" width="765" src="https://user-images.githubusercontent.com/68165163/120393839-9c063180-c300-11eb-9d39-2e564cfe8c56.png">
> 
> Wait- just saw this.

doesn't show in my fork

2021-06-01 21:42 UTC, leahcimto commented
Ok! Merging...

2021-06-01 21:43 UTC, merged